version: '3.9'

services:
  web:
    build: .
    container_name: gestao_web
    command: >
      sh -c "python manage.py migrate && \
             python manage.py collectstatic --noinput && \
             gunicorn gestao_contratos.wsgi:application -b 0.0.0.0:8000 -w 3"
    env_file:
      - .env
    volumes:
      - .:/app
      - ./uploads:/app/uploads
      - ./db.sqlite3:/app/db.sqlite3
      - ./staticfiles:/app/staticfiles
    expose:
      - "8000"
    restart: unless-stopped

  nginx:
    image: nginx:stable
    container_name: gestao_nginx
    depends_on:
      - web
    ports:
      - "80:80"
    volumes:
      - ./deploy/nginx/docker_gestao_contratos.conf:/etc/nginx/conf.d/default.conf:ro
      - ./staticfiles:/usr/share/nginx/html/static:ro
      - ./uploads:/usr/share/nginx/html/media:ro
    restart: unless-stopped