# Generated by Django 5.2 on 2025-04-26 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contrato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status_aprovacao', models.CharField(choices=[('pendente', 'Pendente'), ('aprovado', 'Aprovado'), ('reprovado', 'Reprovado')], default='pendente', max_length=10)),
                ('titulo', models.CharField(max_length=100)),
                ('tipo', models.CharField(choices=[('contrato', 'Contrato'), ('documento', 'Documento')], max_length=10)),
                ('descricao', models.TextField(blank=True)),
                ('data_emissao', models.DateField()),
                ('data_vencimento', models.DateField()),
                ('arquivo', models.FileField(upload_to='uploads/')),
                ('email_alertas', models.EmailField(blank=True, max_length=254, null=True)),
                ('motivo_reprovacao', models.TextField(blank=True, null=True)),
                ('data_envio', models.DateTimeField(auto_now_add=True)),
                ('data_aprovacao', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Contrato',
                'verbose_name_plural': 'Contratos',
            },
        ),
        migrations.CreateModel(
            name='Documento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status_aprovacao', models.CharField(choices=[('pendente', 'Pendente'), ('aprovado', 'Aprovado'), ('reprovado', 'Reprovado')], default='pendente', max_length=10)),
                ('titulo', models.CharField(max_length=100)),
                ('tipo', models.CharField(choices=[('contrato', 'Contrato'), ('documento', 'Documento')], max_length=10)),
                ('descricao', models.TextField(blank=True)),
                ('data_emissao', models.DateField()),
                ('data_vencimento', models.DateField()),
                ('arquivo', models.FileField(upload_to='uploads/')),
                ('email_alertas', models.EmailField(blank=True, max_length=254, null=True)),
                ('motivo_reprovacao', models.TextField(blank=True, null=True)),
                ('data_envio', models.DateTimeField(auto_now_add=True)),
                ('data_aprovacao', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Documento',
                'verbose_name_plural': 'Documentos',
            },
        ),
        migrations.CreateModel(
            name='Perfil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Shopping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('sigla', models.CharField(max_length=10)),
                ('cnpj', models.CharField(max_length=20)),
                ('email_alertas', models.EmailField(blank=True, max_length=254, null=True)),
            ],
        ),
    ]
