# Generated by Django 5.2 on 2025-04-26 20:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('documentos', '0002_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Perfil',
        ),
    ]
