# Generated by Django 5.2 on 2025-05-03 23:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documentos', '0003_delete_perfil'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='documento',
            name='aprovado_por',
        ),
        migrations.RemoveField(
            model_name='documento',
            name='enviado_por',
        ),
        migrations.RemoveField(
            model_name='documento',
            name='shopping',
        ),
        migrations.CreateModel(
            name='RegistroDocumento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('tipo', models.CharField(choices=[('documento', 'Documento'), ('contrato', 'Contrato')], max_length=20)),
                ('descricao', models.TextField(blank=True, null=True)),
                ('data_emissao', models.DateField()),
                ('data_vencimento', models.DateField()),
                ('arquivo', models.FileField(upload_to='uploads/')),
                ('data_envio', models.DateTimeField(auto_now_add=True)),
                ('status_aprovacao', models.CharField(default='pendente', max_length=20)),
                ('data_aprovacao', models.DateTimeField(blank=True, null=True)),
                ('motivo_reprovacao', models.TextField(blank=True, null=True)),
                ('aprovado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='aprovador', to=settings.AUTH_USER_MODEL)),
                ('enviado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('shopping', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='documentos.shopping')),
            ],
        ),
        migrations.DeleteModel(
            name='Contrato',
        ),
        migrations.DeleteModel(
            name='Documento',
        ),
    ]
