# Generated by Django 5.1.6 on 2025-09-29 15:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documentos', '0004_remove_documento_aprovado_por_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registrodocumento',
            name='arquivo',
        ),
        migrations.CreateModel(
            name='AnexoDocumento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arquivo', models.FileField(upload_to='uploads/anexos/')),
                ('data_upload', models.DateTimeField(auto_now_add=True)),
                ('documento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='anexos', to='documentos.registrodocumento')),
            ],
        ),
    ]
