# Generated by Django 5.1.6 on 2025-09-29 17:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documentos', '0005_remove_registrodocumento_arquivo_anexodocumento'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentoObrigatorio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area', models.CharField(max_length=100)),
                ('categoria', models.CharField(max_length=100)),
                ('nome', models.CharField(max_length=150)),
                ('ativo', models.BooleanField(default=True)),
                ('shopping', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='documentos.shopping')),
            ],
            options={
                'verbose_name': 'Documento Obrigatório',
                'verbose_name_plural': 'Documentos Obrigatórios',
            },
        ),
    ]
