# Generated by Django 5.1.6 on 2025-09-29 17:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documentos', '0006_documentoobrigatorio'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='documentoobrigatorio',
            name='marcado_em',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='documentoobrigatorio',
            name='marcado_ok',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='documentoobrigatorio',
            name='marcado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documentos_marcados', to=settings.AUTH_USER_MODEL),
        ),
    ]
