# Generated by Django 5.2 on 2025-10-30 01:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documentos', '0007_documentoobrigatorio_marcado_em_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentoobrigatorio',
            name='documento_vinculado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='premissas_vinculadas', to='documentos.registrodocumento'),
        ),
    ]
