# Generated by Django 5.2 on 2025-10-20 23:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('documentos', '0007_documentoobrigatorio_marcado_em_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Loja',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_loja', models.CharField(max_length=20)),
                ('nome_fantasia', models.CharField(max_length=120)),
                ('razao_social', models.CharField(blank=True, max_length=160)),
                ('cnpj', models.CharField(blank=True, max_length=18)),
                ('piso', models.CharField(blank=True, max_length=50)),
                ('unidade', models.CharField(blank=True, max_length=50)),
                ('segmento', models.CharField(blank=True, max_length=80)),
                ('area_m2', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('contato_nome', models.CharField(blank=True, max_length=120)),
                ('contato_email', models.EmailField(blank=True, max_length=254)),
                ('contato_telefone', models.CharField(blank=True, max_length=30)),
                ('status_loja', models.CharField(choices=[('ativa', 'Ativa'), ('desocupando', 'Desocupando'), ('encerrada', 'Encerrada')], default='ativa', max_length=20)),
                ('canal_notificacao_preferencial', models.CharField(choices=[('email', 'E-mail'), ('whatsapp', 'WhatsApp')], default='email', max_length=20)),
                ('aceite_lgpd', models.BooleanField(default=True)),
                ('observacoes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('shopping', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lojas', to='documentos.shopping')),
            ],
            options={
                'ordering': ['shopping__nome', 'codigo_loja'],
                'unique_together': {('shopping', 'codigo_loja')},
            },
        ),
        migrations.CreateModel(
            name='ApoliceLoja',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_seguro', models.CharField(choices=[('rc', 'Responsabilidade Civil'), ('incendio', 'Incêndio'), ('multirisco', 'Multirisco'), ('danos_eletricos', 'Danos Elétricos'), ('alagamento', 'Alagamento'), ('outros', 'Outros')], max_length=20)),
                ('seguradora', models.CharField(max_length=120)),
                ('numero_apolice', models.CharField(max_length=60)),
                ('endosso', models.CharField(blank=True, max_length=60)),
                ('vigencia_inicio', models.DateField()),
                ('vigencia_fim', models.DateField()),
                ('data_emissao', models.DateField(blank=True, null=True)),
                ('data_recebida', models.DateField(blank=True, null=True)),
                ('status_compliance', models.CharField(choices=[('pendente', 'Pendente'), ('em_analise', 'Em análise'), ('aprovada', 'Aprovada'), ('reprovada', 'Reprovada'), ('expirada', 'Expirada')], default='pendente', max_length=20)),
                ('atende_exigencias', models.BooleanField(blank=True, null=True)),
                ('motivo_nao_conformidade', models.TextField(blank=True)),
                ('valor_premio', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('franquia_padrao', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('condicoes_especiais', models.TextField(blank=True)),
                ('arquivo_apolice', models.FileField(blank=True, upload_to='uploads/apolices/')),
                ('arquivo_certificado', models.FileField(blank=True, upload_to='uploads/apolices/')),
                ('comprovante_pagamento', models.FileField(blank=True, upload_to='uploads/apolices/')),
                ('data_validacao', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('responsavel_validacao', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('loja', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='apolices', to='seguros.loja')),
            ],
            options={
                'ordering': ['-vigencia_fim'],
            },
        ),
    ]
